#world_frame: /map
#odom_frame: h1_tf/odom
#base_link_frame: h1_tf/base_link
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
#map_frame: map

two_d_mode: true
frequency: 50

#odom0: husky_velocity_controller/odom
odom0: neuronbot_diff_drive_controller/odom
odom0_config: [true, true, true,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
